"""add briefcase models and fields

Revision ID: 0371e4504203
Revises: 73aa81bb08a4
Create Date: 2026-03-01 15:28:59.973912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0371e4504203'
down_revision: Union[str, Sequence[str], None] = '73aa81bb08a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_facts_id'), 'case_facts', ['id'], unique=False)
    op.add_column('documents', sa.Column('file_hash', sa.String(length=64), nullable=True))
    op.add_column('documents', sa.Column('tag', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_documents_file_hash'), 'documents', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_file_hash'), table_name='documents')
    op.drop_column('documents', 'tag')
    op.drop_column('documents', 'file_hash')
    op.drop_index(op.f('ix_case_facts_id'), table_name='case_facts')
    op.drop_table('case_facts')
    # ### end Alembic commands ###
