"""Add summary and entities to documents

Revision ID: 16ab8e1ec853
Revises: 8e9b94b95b73
Create Date: 2026-03-01 18:00:42.297387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16ab8e1ec853'
down_revision: Union[str, Sequence[str], None] = '8e9b94b95b73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('entities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'entities')
    op.drop_column('documents', 'summary')
    # ### end Alembic commands ###
