"""add_pisp_id_and_appellation_to_cases

Revision ID: 2782d52467f9
Revises: 24ae0f2ac815
Create Date: 2026-03-30 20:04:53.602664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2782d52467f9'
down_revision: Union[str, Sequence[str], None] = '24ae0f2ac815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('pisp_id', sa.Integer(), nullable=True))
    op.add_column('cases', sa.Column('appellation', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'appellation')
    op.drop_column('cases', 'pisp_id')
    # ### end Alembic commands ###
