"""remove document_chunks and ensure embeddings exists

Revision ID: 3009fc08ea5d
Revises: 153361d2e108
Create Date: 2026-04-11 08:09:21.013225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3009fc08ea5d'
down_revision: Union[str, Sequence[str], None] = '153361d2e108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create embeddings table if it somehow doesn't exist (safety)
    op.execute("""
        CREATE TABLE IF NOT EXISTS embeddings (
            id SERIAL PRIMARY KEY,
            case_id INTEGER,
            entity_type VARCHAR(50) NOT NULL,
            entity_id INTEGER NOT NULL,
            content TEXT,
            embedding VECTOR(768),
            metadata_json JSON,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
        )
    """)
    
    # Ensure case_id exists if table was created previously without it
    op.execute("ALTER TABLE embeddings ADD COLUMN IF NOT EXISTS case_id INTEGER")
    
    op.execute("CREATE INDEX IF NOT EXISTS ix_embeddings_case_id ON embeddings (case_id)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_embeddings_entity_type ON embeddings (entity_type)")
    op.execute("CREATE INDEX IF NOT EXISTS ix_embeddings_entity_id ON embeddings (entity_id)")

    # Migrate data from document_chunks to embeddings
    # We check if document_chunks has data to avoid empty inserts or errors if it was already migrated
    op.execute("""
        INSERT INTO embeddings (case_id, entity_type, entity_id, content, embedding, created_at)
        SELECT d.case_id, 'document', dc.document_id, dc.content, dc.embedding, NOW()
        FROM document_chunks dc
        JOIN documents d ON dc.document_id = d.id
        ON CONFLICT DO NOTHING
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('document_chunks_document_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('document_chunks_pkey'))
    )
    op.create_index(op.f('ix_document_chunks_id'), 'document_chunks', ['id'], unique=False)
    # ### end Alembic commands ###
