"""Expand saos models with extra fields

Revision ID: 585df82880bb
Revises: ad45c066d7cc
Create Date: 2026-03-29 20:54:51.698454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '585df82880bb'
down_revision: Union[str, Sequence[str], None] = 'ad45c066d7cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_messages')
    op.add_column('saved_judgments', sa.Column('court_type', sa.String(length=50), nullable=True))
    op.add_column('saved_judgments', sa.Column('division_name', sa.Text(), nullable=True))
    op.add_column('saved_judgments', sa.Column('judges', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('saved_judgments', 'judges')
    op.drop_column('saved_judgments', 'division_name')
    op.drop_column('saved_judgments', 'court_type')
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    # ### end Alembic commands ###
