"""pisp upgrade

Revision ID: 6a41a982bfcc
Revises: f3f13b638972
Create Date: 2026-03-28 19:49:39.494239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a41a982bfcc'
down_revision: Union[str, Sequence[str], None] = 'f3f13b638972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_entities', sa.Column('representatives', sa.JSON(), nullable=True))
    op.alter_column('case_entities', 'type',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.add_column('documents', sa.Column('created_date', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('modification_date', sa.String(length=50), nullable=True))
    op.drop_column('documents', 's3_key_source')
    op.drop_column('documents', 'source_download_link')
    op.drop_column('documents', 's3_key_pdf')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('s3_key_pdf', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('source_download_link', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('s3_key_source', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('documents', 'modification_date')
    op.drop_column('documents', 'created_date')
    op.alter_column('case_entities', 'type',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_column('case_entities', 'representatives')
    # ### end Alembic commands ###
