"""Add signature to cases

Revision ID: 73aa81bb08a4
Revises: ac2221142911
Create Date: 2026-03-01 12:48:00.081468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73aa81bb08a4'
down_revision: Union[str, Sequence[str], None] = 'ac2221142911'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('signature', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'signature')
    # ### end Alembic commands ###
