"""aktowka_models

Revision ID: 9833a41bd7d0
Revises: 0371e4504203
Create Date: 2026-03-01 16:18:37.958363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9833a41bd7d0'
down_revision: Union[str, Sequence[str], None] = '0371e4504203'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_case_facts_id', table_name='case_facts')
    op.drop_table('case_facts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_facts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source_doc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_facts_case_id_fkey'),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], name='case_facts_source_doc_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='case_facts_pkey')
    )
    op.create_index('ix_case_facts_id', 'case_facts', ['id'], unique=False)
    # ### end Alembic commands ###
