"""add api_key to app_settings

Revision ID: a834fbfba163
Revises: ad4bc6e63ea4
Create Date: 2026-04-07 12:11:33.159470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a834fbfba163'
down_revision: Union[str, Sequence[str], None] = 'ad4bc6e63ea4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_settings', sa.Column('api_key', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_settings', 'api_key')
    # ### end Alembic commands ###
