"""Add saos models

Revision ID: ad45c066d7cc
Revises: df11a5e0d509
Create Date: 2026-03-29 19:43:55.732952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad45c066d7cc'
down_revision: Union[str, Sequence[str], None] = 'df11a5e0d509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_judgments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saos_id', sa.Integer(), nullable=False),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('judgment_date', sa.String(length=50), nullable=True),
    sa.Column('court_name', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'AI', name='judgmentsource'), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saved_judgments_id'), 'saved_judgments', ['id'], unique=False)
    op.create_index(op.f('ix_saved_judgments_saos_id'), 'saved_judgments', ['saos_id'], unique=False)
    op.drop_table('chat_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.drop_index(op.f('ix_saved_judgments_saos_id'), table_name='saved_judgments')
    op.drop_index(op.f('ix_saved_judgments_id'), table_name='saved_judgments')
    op.drop_table('saved_judgments')
    # ### end Alembic commands ###
