"""add_case_relations

Revision ID: df11a5e0d509
Revises: 00982d2f1670
Create Date: 2026-03-29 18:59:34.990328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df11a5e0d509'
down_revision: Union[str, Sequence[str], None] = '00982d2f1670'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_relations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pisp_id', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('relation_type', sa.String(length=100), nullable=True),
    sa.Column('authority', sa.String(length=255), nullable=True),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('receipt_date', sa.String(length=50), nullable=True),
    sa.Column('decission_date', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_relations_id'), 'case_relations', ['id'], unique=False)
    op.drop_constraint(op.f('case_facts_source_doc_id_fkey'), 'case_facts', type_='foreignkey')
    op.create_foreign_key(None, 'case_facts', 'documents', ['source_doc_id'], ['id'])
    op.alter_column('documents', 'suggested_facts',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'suggested_facts',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'case_facts', type_='foreignkey')
    op.create_foreign_key(op.f('case_facts_source_doc_id_fkey'), 'case_facts', 'documents', ['source_doc_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_case_relations_id'), table_name='case_relations')
    op.drop_table('case_relations')
    # ### end Alembic commands ###
