"""restore pisp 3.0 fields and models

Revision ID: f3f13b638972
Revises: 16ab8e1ec853
Create Date: 2026-03-28 19:10:13.009401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f13b638972'
down_revision: Union[str, Sequence[str], None] = '16ab8e1ec853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pisp_id', sa.Integer(), nullable=True),
    sa.Column('pisp_case_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('court_name', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('party', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('full_document_name', sa.Text(), nullable=True),
    sa.Column('receiver', sa.String(length=255), nullable=True),
    sa.Column('document_name', sa.Text(), nullable=True),
    sa.Column('activity', sa.Text(), nullable=True),
    sa.Column('submitted_by', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_activities_id'), 'case_activities', ['id'], unique=False)
    op.create_table('case_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pisp_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('date_from', sa.String(length=50), nullable=True),
    sa.Column('date_to', sa.String(length=50), nullable=True),
    sa.Column('gained_access_date', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.String(length=50), nullable=True),
    sa.Column('modification_date', sa.String(length=50), nullable=True),
    sa.Column('has_access', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_entities_id'), 'case_entities', ['id'], unique=False)
    op.create_table('case_hearings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('pisp_id', sa.Integer(), nullable=True),
    sa.Column('signature', sa.String(length=100), nullable=True),
    sa.Column('court', sa.String(length=255), nullable=True),
    sa.Column('date', sa.String(length=50), nullable=True),
    sa.Column('room', sa.String(length=50), nullable=True),
    sa.Column('procedure', sa.String(length=255), nullable=True),
    sa.Column('judge', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('value', sa.String(length=100), nullable=True),
    sa.Column('eprotocol', sa.String(length=20), nullable=True),
    sa.Column('eprotocol_id', sa.Integer(), nullable=True),
    sa.Column('eprotocol_video_path', sa.Text(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('video_archivization_date', sa.String(length=50), nullable=True),
    sa.Column('transcription_files_present', sa.String(length=50), nullable=True),
    sa.Column('created_date', sa.String(length=50), nullable=True),
    sa.Column('modification_date', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_hearings_id'), 'case_hearings', ['id'], unique=False)
    op.add_column('cases', sa.Column('court', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('receipt_date', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('conclusion_date', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('publication_date', sa.String(length=50), nullable=True))
    op.add_column('cases', sa.Column('case_subject', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('referent', sa.String(length=255), nullable=True))
    op.add_column('cases', sa.Column('claim_value', sa.String(length=100), nullable=True))
    op.add_column('cases', sa.Column('resolution', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('main_entities', sa.Text(), nullable=True))
    op.drop_index('ix_cases_title', table_name='cases')
    op.add_column('documents', sa.Column('pisp_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('create_date', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('publication_date', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('document_name', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('document_type', sa.String(length=100), nullable=True))
    op.add_column('documents', sa.Column('downloaded', sa.String(length=20), nullable=True))
    op.add_column('documents', sa.Column('document_checksum', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('writing_id', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('writing_attachment_type', sa.String(length=255), nullable=True))
    op.add_column('documents', sa.Column('docs_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('download_link', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('source_download_link', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('s3_key_source', sa.String(length=512), nullable=True))
    op.add_column('documents', sa.Column('s3_key_pdf', sa.String(length=512), nullable=True))
    op.alter_column('documents', 'file_hash',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('documents', 'tag',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index('ix_documents_file_hash', table_name='documents')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_file_hash', 'documents', ['file_hash'], unique=False)
    op.alter_column('documents', 'tag',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.alter_column('documents', 'file_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.drop_column('documents', 's3_key_pdf')
    op.drop_column('documents', 's3_key_source')
    op.drop_column('documents', 'source_download_link')
    op.drop_column('documents', 'download_link')
    op.drop_column('documents', 'docs_count')
    op.drop_column('documents', 'writing_attachment_type')
    op.drop_column('documents', 'writing_id')
    op.drop_column('documents', 'document_checksum')
    op.drop_column('documents', 'downloaded')
    op.drop_column('documents', 'document_type')
    op.drop_column('documents', 'document_name')
    op.drop_column('documents', 'publication_date')
    op.drop_column('documents', 'create_date')
    op.drop_column('documents', 'pisp_id')
    op.create_index('ix_cases_title', 'cases', ['title'], unique=False)
    op.drop_column('cases', 'main_entities')
    op.drop_column('cases', 'resolution')
    op.drop_column('cases', 'claim_value')
    op.drop_column('cases', 'referent')
    op.drop_column('cases', 'case_subject')
    op.drop_column('cases', 'publication_date')
    op.drop_column('cases', 'conclusion_date')
    op.drop_column('cases', 'receipt_date')
    op.drop_column('cases', 'department')
    op.drop_column('cases', 'court')
    op.drop_index(op.f('ix_case_hearings_id'), table_name='case_hearings')
    op.drop_table('case_hearings')
    op.drop_index(op.f('ix_case_entities_id'), table_name='case_entities')
    op.drop_table('case_entities')
    op.drop_index(op.f('ix_case_activities_id'), table_name='case_activities')
    op.drop_table('case_activities')
    # ### end Alembic commands ###
